### ISSUE TITLE
contribute

### ISSUE THREAD

**Issue by AgrumeStly** [TNTtian/OIer-meet#1]
提供数据格式：**`比赛名称`+`空格`+`准考证号`+`空格`+`所在OJ`+`@`+`用户名`+`(uid=`+`所在OJ的uid`+`)`**  

例：  
`CSp2020-S1 BJ-00653 Luogu@Trotyl(uid=128369)`  
`NOIp1919-pj BJ-00810 Luogu@Trotyl(uid=128369)`  

**若未按照此格式提交，概不接受**

-----

Provide data format: **`Competition name`+`space` +`admission number`+`space`+`OJ's name`+`@`+`user name` + `(uid=` +`uid`+`)`**

Eg.  
`CSp2020-S1 BJ-00653 Luogu@Trotyl(uid=128369)`  
`NOIp1919-pj BJ-00810 Luogu@Trotyl(uid=128369)`  

**If it is not submitted in this format, it will not be accepted**

------ 

### 感谢您的贡献！

------

### Thank you for your contribution!

---

（贡献将在 14 天内处理，若未完成欢迎提醒催促）

**Comment by AgrumeStly** [comment]
再一次感谢您的贡献！

Thank you for your contribution again!

**Comment by hanyuchen2019** [comment]
CSP2020-S1 AH-00267 Luogu@hanyuchen2019(uid=277757)

**Comment by hanyuchen2019** [comment]
CSP2020-S1 AH-00267 Luogu@hanyuchen2019(uid=277757)

**Comment by UserUnknownX** [comment]
> CSP2020-S1 AH-00267 Luogu@hanyuchen2019(uid=277757)
> （我不会用github）

帮你pr了

**Comment by ghost** [comment]
留下名（不然有可能收不到消息提醒
